version: "3.9"

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - tag=debug
    ports:
      - 44341:44341
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - tag=debug
